version: '3.5'

services:
  edc-provider:
    #build:
    #  context: ../../
    #  dockerfile: ./launchers/mdsp-connector/provider.Dockerfile
    image: mdsp-connector_edc-provider:latest
    container_name: 'catena-x-edc-provider'
    ports:
      - 8181:8181
      - 8182:8182
      - 8282:8282
    environment:
      - IDS_WEBHOOK_ADDRESS=http://catena-x-edc-provider:8282

  edc-consumer:
    #build:
    #  context: ../../
    #  dockerfile: ./launchers/mdsp-connector/consumer.Dockerfile
    image: mdsp-connector_edc-consumer:latest
    container_name: 'catena-x-edc-consumer'
    ports:
      - 9191:9191
      - 9192:9192
      - 9292:9292
    environment:
      - IDS_WEBHOOK_ADDRESS=http://catena-x-edc-consumer:9292
    
