[metadata]
format.version = "1.1"

[versions]
azure-mgmt = "1.41.4"
okhttp = "4.10.0"
titanium = "1.3.2"
jackson = "2.14.2"
jackarta-json = "2.0.1"
jetty-jakarta-servlet-api = "5.0.2"
json-unit = "2.37.0"
junit-pioneer = "2.0.0"
opentelemetry-proto = "0.14.0-alpha"

[libraries]
azure-mgmt-resources = { module = "com.microsoft.azure:azure-mgmt-resources", version.ref = "azure-mgmt" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
dnsOverHttps = { module = "com.squareup.okhttp3:okhttp-dnsoverhttps", version.ref = "okhttp" }
titaniumJsonLd = { module = "com.apicatalog:titanium-json-ld", version.ref = "titanium" }
jacksonJsonP = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jakarta-jsonp", version.ref = "jackson" }
jakartaJson = { module = "org.glassfish:jakarta.json", version.ref = "jackarta-json" }
jetty-jakarta-servlet-api = { module = "org.eclipse.jetty.toolchain:jetty-jakarta-servlet-api", version.ref = "jetty-jakarta-servlet-api" }
json-unit = { module = "net.javacrumbs.json-unit:json-unit", version.ref = "json-unit" }
json-unit-assertj = { module = "net.javacrumbs.json-unit:json-unit-assertj", version.ref = "json-unit" }
json-unit-json-path = { module = "net.javacrumbs.json-unit:json-unit-json-path", version.ref = "json-unit" }
junit-pioneer = { module = "org.junit-pioneer:junit-pioneer", version.ref = "junit-pioneer" }
opentelemetry-proto = { module = "io.opentelemetry.proto:opentelemetry-proto", version.ref = "opentelemetry-proto" }

[bundles]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
