[metadata]
format.version = "1.1"

[versions]
okhttp = "4.10.0"
titanium = "1.3.1"
jackson = "2.14.2"
jackarta-json = "2.0.1"

[libraries]
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
dnsOverHttps = { module = "com.squareup.okhttp3:okhttp-dnsoverhttps", version.ref = "okhttp" }
titaniumJsonLd = { module = "com.apicatalog:titanium-json-ld", version.ref = "titanium" }
jacksonJsonP = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jakarta-jsonp", version.ref = "jackson" }
jakartaJson = { module = "org.glassfish:jakarta.json", version.ref = "jackarta-json" }

[bundles]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
