---
name: "Check API version file changed"
description: "Checks that the API version.json file was changed too if the API module was modified"
inputs:
  apiDirectory:
    required: true
    description: "The directory where the API module is located. Relative to the repo root."
  apiVersionFile:
    required: true
    description: "The path to the JSON file that contains API versioning information, relative to the repo root."


runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Inspect changeset if version file changed
      shell: bash
      run: |
        # main branch is not checked out by default
        git fetch --no-tags --prune --no-recurse-submodules --depth=1 origin main:main

        # check if there was a change any of the API modules. the last "grep" parses the result of "wc" into a number
        apiChanges=$(git diff --name-status main | grep "${{ inputs.apiDirectory }}" | wc -l | grep -o "[0-9]\+")
        if [[ $apiChanges = 0 ]]; then
          echo "There were no changes in the API"
          exit 0;
        else 
          echo "There are $apiChanges changed files in the API, will check if version.json was modified."
          # if so, check if the changeset also contains the `version.json` file
          changes=$(git diff --name-status main | grep "${{ inputs.apiVersionFile }}" |  wc -l | grep -o "[0-9]\+")
          if [[ $changes < 1 ]]; then
            echo "::error file=./${{ inputs.apiVersionFile }},line=1::Bumping the version is required after a change to the API"
            exit 100;
          fi
          exit 0;
        fi