openapi: 3.0.1
paths:
  /contractnegotitations/{id}/cancel:
    post:
      operationId: cancelNegotiation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /contractnegotitations/{id}/decline:
    post:
      operationId: declineNegotiation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json: {}
  /contractnegotitations/{id}:
    get:
      operationId: getNegotiation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContractNegotiationDto'
  /contractnegotitations/{id}/state:
    get:
      operationId: getNegotiationState
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: string
  /contractnegotitations:
    get:
      operationId: getNegotiations
      parameters:
      - name: offset
        in: query
        schema:
          type: integer
          format: int32
      - name: limit
        in: query
        schema:
          type: integer
          format: int32
      - name: filter
        in: query
        schema:
          type: string
      - name: sort
        in: query
        schema:
          type: string
          enum:
          - ASC
          - DESC
      - name: sortField
        in: query
        schema:
          type: string
      responses:
        default:
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContractNegotiationDto'
components:
  schemas:
    ContractNegotiationDto:
      type: object
      properties:
        id:
          type: string
        counterPartyAddress:
          type: string
        protocol:
          type: string
        type:
          type: string
          enum:
          - CONSUMER
          - PROVIDER
        state:
          type: string
        errorDetail:
          type: string
        contractAgreementId:
          type: string
