name: 'Dependency Review'

on:
  push:
    branches:
      - main
  pull_request_target:
    paths:
      - "gradle/libs.versions.toml"

permissions:
  contents: read

jobs:
  check:
    uses: eclipse-edc/.github/.github/workflows/dependency-check.yml@main
    secrets: inherit
