name: Integration Tests

on: [ push, pull_request ]

jobs:

  Azure-Storage-Integration-Test:
    runs-on: ubuntu-latest

    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
        env:
          AZURITE_ACCOUNTS: account1:key1;account2:key2

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Azure Storage Tests
        run: ./gradlew -p extensions/azure test -DincludeTags="AzureStorageIntegrationTest"

  Azure-CosmosDB-Integration-Test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      # Cosmos DB Emulator is preinstalled on GitHub Actions workers
      - name: Launch Cosmos DB Emulator
        run: |
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          Start-CosmosDbEmulator -Timeout 1200

      - name: Azure CosmosDB Tests
        run: ./gradlew -p extensions/azure/cosmos test -DincludeTags="AzureCosmosDbIntegrationTest"

  Aws-Integration-Test:
    runs-on: ubuntu-latest

    services:
      minio:
        image: bitnami/minio:latest
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: root
          MINIO_ROOT_PASSWORD: password

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: AWS S3 Tests
        env:
          S3_ACCESS_KEY_ID: root
          S3_SECRET_ACCESS_KEY: password
        run: ./gradlew -p extensions/aws/s3 test -DincludeTags="AwsS3IntegrationTest"

      - name: AWS S3 StatusChecker Test
        env:
          S3_ACCESS_KEY_ID: root
          S3_SECRET_ACCESS_KEY: password
        run: ./gradlew extensions:aws:s3:s3-data-operator:check

  Daps-Integration-Test:
    runs-on: ubuntu-latest

    steps:
      - name: reset permissions to permit checkout (because the omejdn volumes)
        run: sudo chown -R $USER:$USER ${{ github.workspace }}

      - uses: actions/checkout@v2

      - run: docker run -d --rm -p 4567:4567 -v ${{ github.workspace }}/extensions/iam/daps/src/test/resources/config:/opt/config -v ${{ github.workspace }}/extensions/iam/daps/src/test/resources/keys:/opt/keys ghcr.io/fraunhofer-aisec/omejdn-server:1.3.1

      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Daps Integration Tests
        run: ./gradlew -p extensions/iam/daps test -DincludeTags="DapsIntegrationTest"
