name: Build/Test

on: [ push ]

jobs:
  Unit-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Gradle Test Core
        env:
          INTEGRATION_TEST: false
        run: ./gradlew clean check

#  Integration-Test:
#    runs-on: ubuntu-latest
#    services:
#      nifi:
#        image: docker.pkg.github.com/microsoft/data-appliance-gx/nifi
#        credentials:
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#        ports:
#          - 8080:8080
#          - 8888:8888
#      atlas:
#        image: sburn/apache-atlas
#        ports:
#          - 21000:21000
#        options: --entrypoint /opt/apache-atlas-2.1.0/bin/atlas_start.py
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up JDK 11
#        uses: actions/setup-java@v1
#        with:
#          java-version: '11'
#
#      - name: Test Nifi Integration
#        if: ${{ false }}
#        env:
#          AZ_STORAGE_SAS: ${{ secrets.AZ_STORAGE_SAS }}
#          NIFI_API_AUTH: ${{ secrets.NIFI_API_AUTH }}
#          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
#          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
#        run: ./gradlew samples:copy-with-nifi:check
#
#      - name: Test Atlas Integration
#        run: ./gradlew extensions:atlas:check


  Integration-Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Atlas integration Test
        env:
          RUN_INTEGRATION_TEST: true
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AZ_STORAGE_SAS: ${{ secrets.AZ_STORAGE_SAS }}
          AZ_STORAGE_KEY: ${{ secrets.AZ_STORAGE_KEY }}
        run: ./gradlew extensions:atlas:check

      - name: Azure Vault Test
        env:
          RUN_INTEGRATION_TEST: true
          AZ_STORAGE_SAS: ${{ secrets.AZ_STORAGE_SAS }}
        run: ./gradlew extensions:azure:vault:check

      - name: Blob Store StatusChecker Test
        env:
          RUN_INTEGRATION_TEST: true
          AZ_STORAGE_SAS: ${{ secrets.AZ_STORAGE_KEY }}
        run: ./gradlew extensions:azure:vault:check

      - name: CosmosDB Transfer Process Store Test
        env:
          RUN_INTEGRATION_TEST: true
          COSMOS_KEY: ${{ secrets.COSMOS_KEY }}
        run: ./gradlew extensions:azure:transfer-process-store-cosmos:check

      - name: AWS S3 StatusChecker Test
        env:
          RUN_INTEGRATION_TEST: true
          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          S3_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
        run: ./gradlew extensions:aws:s3:provision:check